import type { Metadata } from "next";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";
import { ToastProvider } from "@/components/providers/toast-provider";

import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Shift Academy o'quv markazi",
  description: "Generated by create next app",
};

const josefin = Josefin_Sans({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={josefin.className}>
        <div className="bg-[#001E36] min-h-screen">
          <ToastProvider />
          <NextTopLoader
            color="#2299DD"
            initialPosition={0.08}
            crawlSpeed={200}
            height={4}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px #2299DD,0 0 5px #2299DD"
            zIndex={1600}
            showAtBottom={false}
          />
          {children}
        </div>
      </body>
    </html>
  );
}
