import type { Metadata } from "next";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Shift Academy o'quv markazi",
  description: "Generated by create next app",
};

const josefin = Josefin_Sans({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={josefin.className}>
        <div className="bg-[#001E36] min-h-screen">{children}</div>
      </body>
    </html>
  );
}
